#ifndef _AST_AST_T_H
#define _AST_AST_T_H

#include "util/c_std.h"

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// Abstract syntax tree

#define TIdentifier unsigned long
#define TChar int8_t
#define TInt int32_t
#define TLong int64_t
#define TUChar uint8_t
#define TUInt uint32_t
#define TULong uint64_t
#define TDouble double

#define AST_T int

// Frontend symbol table
#define AST_Type_t 0
#define AST_Char_t 1
#define AST_SChar_t 2
#define AST_UChar_t 3
#define AST_Int_t 4
#define AST_Long_t 5
#define AST_UInt_t 6
#define AST_ULong_t 7
#define AST_Double_t 8
#define AST_Void_t 9
#define AST_FunType_t 10
#define AST_Pointer_t 11
#define AST_Array_t 12
#define AST_Structure_t 13
#define AST_StaticInit_t 14
#define AST_IntInit_t 15
#define AST_LongInit_t 16
#define AST_UIntInit_t 17
#define AST_ULongInit_t 18
#define AST_CharInit_t 19
#define AST_UCharInit_t 20
#define AST_DoubleInit_t 21
#define AST_ZeroInit_t 22
#define AST_StringInit_t 23
#define AST_PointerInit_t 24
#define AST_InitialValue_t 25
#define AST_Tentative_t 26
#define AST_Initial_t 27
#define AST_NoInitializer_t 28
#define AST_IdentifierAttr_t 29
#define AST_FunAttr_t 30
#define AST_StaticAttr_t 31
#define AST_ConstantAttr_t 32
#define AST_LocalAttr_t 33
#define AST_Symbol_t 34
#define AST_StructMember_t 35
#define AST_StructTypedef_t 36

// Backend symbol table
#define AST_AssemblyType_t 37
#define AST_Byte_t 38
#define AST_LongWord_t 39
#define AST_QuadWord_t 40
#define AST_BackendDouble_t 41
#define AST_ByteArray_t 42
#define AST_BackendSymbol_t 43
#define AST_BackendObj_t 44
#define AST_BackendFun_t 45

// Frontend abstract syntax tree
#define AST_CConst_t 46
#define AST_CConstInt_t 47
#define AST_CConstLong_t 48
#define AST_CConstUInt_t 49
#define AST_CConstULong_t 50
#define AST_CConstDouble_t 51
#define AST_CConstChar_t 52
#define AST_CConstUChar_t 53
#define AST_CStringLiteral_t 54
#define AST_CUnaryOp_t 55
#define AST_CComplement_t 56
#define AST_CNegate_t 57
#define AST_CNot_t 58
#define AST_CPrefix_t 59
#define AST_CPostfix_t 60
#define AST_CBinaryOp_t 61
#define AST_CAdd_t 62
#define AST_CSubtract_t 63
#define AST_CMultiply_t 64
#define AST_CDivide_t 65
#define AST_CRemainder_t 66
#define AST_CBitAnd_t 67
#define AST_CBitOr_t 68
#define AST_CBitXor_t 69
#define AST_CBitShiftLeft_t 70
#define AST_CBitShiftRight_t 71
#define AST_CBitShrArithmetic_t 72
#define AST_CAnd_t 73
#define AST_COr_t 74
#define AST_CEqual_t 75
#define AST_CNotEqual_t 76
#define AST_CLessThan_t 77
#define AST_CLessOrEqual_t 78
#define AST_CGreaterThan_t 79
#define AST_CGreaterOrEqual_t 80
#define AST_CAbstractDeclarator_t 81
#define AST_CAbstractPointer_t 82
#define AST_CAbstractArray_t 83
#define AST_CAbstractBase_t 84
#define AST_CParam_t 85
#define AST_CDeclarator_t 86
#define AST_CIdent_t 87
#define AST_CPointerDeclarator_t 88
#define AST_CArrayDeclarator_t 89
#define AST_CFunDeclarator_t 90
#define AST_CExp_t 91
#define AST_CConstant_t 92
#define AST_CString_t 93
#define AST_CVar_t 94
#define AST_CCast_t 95
#define AST_CUnary_t 96
#define AST_CBinary_t 97
#define AST_CAssignment_t 98
#define AST_CConditional_t 99
#define AST_CFunctionCall_t 100
#define AST_CDereference_t 101
#define AST_CAddrOf_t 102
#define AST_CSubscript_t 103
#define AST_CSizeOf_t 104
#define AST_CSizeOfT_t 105
#define AST_CDot_t 106
#define AST_CArrow_t 107
#define AST_CStatement_t 108
#define AST_CReturn_t 109
#define AST_CExpression_t 110
#define AST_CIf_t 111
#define AST_CGoto_t 112
#define AST_CLabel_t 113
#define AST_CCompound_t 114
#define AST_CWhile_t 115
#define AST_CDoWhile_t 116
#define AST_CFor_t 117
#define AST_CSwitch_t 118
#define AST_CCase_t 119
#define AST_CDefault_t 120
#define AST_CBreak_t 121
#define AST_CContinue_t 122
#define AST_CNull_t 123
#define AST_CForInit_t 124
#define AST_CInitDecl_t 125
#define AST_CInitExp_t 126
#define AST_CBlock_t 127
#define AST_CB_t 128
#define AST_CBlockItem_t 129
#define AST_CS_t 130
#define AST_CD_t 131
#define AST_CStorageClass_t 132
#define AST_CStatic_t 133
#define AST_CExtern_t 134
#define AST_CInitializer_t 135
#define AST_CSingleInit_t 136
#define AST_CCompoundInit_t 137
#define AST_CMemberDeclaration_t 138
#define AST_CStructDeclaration_t 139
#define AST_CFunctionDeclaration_t 140
#define AST_CVariableDeclaration_t 141
#define AST_CDeclaration_t 142
#define AST_CFunDecl_t 143
#define AST_CVarDecl_t 144
#define AST_CStructDecl_t 145
#define AST_CProgram_t 146

// Intermediate abstract syntax tree
#define AST_TacUnaryOp_t 147
#define AST_TacComplement_t 148
#define AST_TacNegate_t 149
#define AST_TacNot_t 150
#define AST_TacBinaryOp_t 151
#define AST_TacAdd_t 152
#define AST_TacSubtract_t 153
#define AST_TacMultiply_t 154
#define AST_TacDivide_t 155
#define AST_TacRemainder_t 156
#define AST_TacBitAnd_t 157
#define AST_TacBitOr_t 158
#define AST_TacBitXor_t 159
#define AST_TacBitShiftLeft_t 160
#define AST_TacBitShiftRight_t 161
#define AST_TacBitShrArithmetic_t 162
#define AST_TacEqual_t 163
#define AST_TacNotEqual_t 164
#define AST_TacLessThan_t 165
#define AST_TacLessOrEqual_t 166
#define AST_TacGreaterThan_t 167
#define AST_TacGreaterOrEqual_t 168
#define AST_TacValue_t 169
#define AST_TacConstant_t 170
#define AST_TacVariable_t 171
#define AST_TacExpResult_t 172
#define AST_TacPlainOperand_t 173
#define AST_TacDereferencedPointer_t 174
#define AST_TacSubObject_t 175
#define AST_TacInstruction_t 176
#define AST_TacReturn_t 177
#define AST_TacSignExtend_t 178
#define AST_TacTruncate_t 179
#define AST_TacZeroExtend_t 180
#define AST_TacDoubleToInt_t 181
#define AST_TacDoubleToUInt_t 182
#define AST_TacIntToDouble_t 183
#define AST_TacUIntToDouble_t 184
#define AST_TacFunCall_t 185
#define AST_TacUnary_t 186
#define AST_TacBinary_t 187
#define AST_TacCopy_t 188
#define AST_TacGetAddress_t 189
#define AST_TacLoad_t 190
#define AST_TacStore_t 191
#define AST_TacAddPtr_t 192
#define AST_TacCopyToOffset_t 193
#define AST_TacCopyFromOffset_t 194
#define AST_TacJump_t 195
#define AST_TacJumpIfZero_t 196
#define AST_TacJumpIfNotZero_t 197
#define AST_TacLabel_t 198
#define AST_TacTopLevel_t 199
#define AST_TacFunction_t 200
#define AST_TacStaticVariable_t 201
#define AST_TacStaticConstant_t 202
#define AST_TacProgram_t 203

// Backend abstract syntax tree
#define AST_AsmReg_t 204
#define AST_AsmAx_t 205
#define AST_AsmBx_t 206
#define AST_AsmCx_t 207
#define AST_AsmDx_t 208
#define AST_AsmDi_t 209
#define AST_AsmSi_t 210
#define AST_AsmR8_t 211
#define AST_AsmR9_t 212
#define AST_AsmR10_t 213
#define AST_AsmR11_t 214
#define AST_AsmR12_t 215
#define AST_AsmR13_t 216
#define AST_AsmR14_t 217
#define AST_AsmR15_t 218
#define AST_AsmSp_t 219
#define AST_AsmBp_t 220
#define AST_AsmXMM0_t 221
#define AST_AsmXMM1_t 222
#define AST_AsmXMM2_t 223
#define AST_AsmXMM3_t 224
#define AST_AsmXMM4_t 225
#define AST_AsmXMM5_t 226
#define AST_AsmXMM6_t 227
#define AST_AsmXMM7_t 228
#define AST_AsmXMM8_t 229
#define AST_AsmXMM9_t 230
#define AST_AsmXMM10_t 231
#define AST_AsmXMM11_t 232
#define AST_AsmXMM12_t 233
#define AST_AsmXMM13_t 234
#define AST_AsmXMM14_t 235
#define AST_AsmXMM15_t 236
#define AST_AsmCondCode_t 237
#define AST_AsmE_t 238
#define AST_AsmNE_t 239
#define AST_AsmG_t 240
#define AST_AsmGE_t 241
#define AST_AsmL_t 242
#define AST_AsmLE_t 243
#define AST_AsmA_t 244
#define AST_AsmAE_t 245
#define AST_AsmB_t 246
#define AST_AsmBE_t 247
#define AST_AsmP_t 248
#define AST_AsmOperand_t 249
#define AST_AsmImm_t 250
#define AST_AsmRegister_t 251
#define AST_AsmPseudo_t 252
#define AST_AsmMemory_t 253
#define AST_AsmData_t 254
#define AST_AsmPseudoMem_t 255
#define AST_AsmIndexed_t 256
#define AST_AsmBinaryOp_t 257
#define AST_AsmAdd_t 258
#define AST_AsmSub_t 259
#define AST_AsmMult_t 260
#define AST_AsmDivDouble_t 261
#define AST_AsmBitAnd_t 262
#define AST_AsmBitOr_t 263
#define AST_AsmBitXor_t 264
#define AST_AsmBitShiftLeft_t 265
#define AST_AsmBitShiftRight_t 266
#define AST_AsmBitShrArithmetic_t 267
#define AST_AsmUnaryOp_t 268
#define AST_AsmNot_t 269
#define AST_AsmNeg_t 270
#define AST_AsmShr_t 271
#define AST_AsmInstruction_t 272
#define AST_AsmMov_t 273
#define AST_AsmMovSx_t 274
#define AST_AsmMovZeroExtend_t 275
#define AST_AsmLea_t 276
#define AST_AsmCvttsd2si_t 277
#define AST_AsmCvtsi2sd_t 278
#define AST_AsmUnary_t 279
#define AST_AsmBinary_t 280
#define AST_AsmCmp_t 281
#define AST_AsmIdiv_t 282
#define AST_AsmDiv_t 283
#define AST_AsmCdq_t 284
#define AST_AsmJmp_t 285
#define AST_AsmJmpCC_t 286
#define AST_AsmSetCC_t 287
#define AST_AsmLabel_t 288
#define AST_AsmPush_t 289
#define AST_AsmPop_t 290
#define AST_AsmCall_t 291
#define AST_AsmRet_t 292
#define AST_AsmTopLevel_t 293
#define AST_AsmFunction_t 294
#define AST_AsmStaticVariable_t 295
#define AST_AsmStaticConstant_t 296
#define AST_AsmProgram_t 297

#endif
